// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrmUIClient is the client API for OrmUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrmUIClient interface {
	// ListEngineSpecs returns a list of Object Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (OrmUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type ormUIClient struct {
	cc grpc.ClientConnInterface
}

func NewOrmUIClient(cc grpc.ClientConnInterface) OrmUIClient {
	return &ormUIClient{cc}
}

func (c *ormUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (OrmUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &OrmUI_ServiceDesc.Streams[0], "/v1.OrmUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &ormUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OrmUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type ormUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *ormUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ormUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.OrmUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrmUIServer is the server API for OrmUI service.
// All implementations must embed UnimplementedOrmUIServer
// for forward compatibility
type OrmUIServer interface {
	// ListEngineSpecs returns a list of Object Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, OrmUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedOrmUIServer()
}

// UnimplementedOrmUIServer must be embedded to have forward compatible implementations.
type UnimplementedOrmUIServer struct {
}

func (UnimplementedOrmUIServer) ListEngineSpecs(*ListEngineSpecsRequest, OrmUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedOrmUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedOrmUIServer) mustEmbedUnimplementedOrmUIServer() {}

// UnsafeOrmUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrmUIServer will
// result in compilation errors.
type UnsafeOrmUIServer interface {
	mustEmbedUnimplementedOrmUIServer()
}

func RegisterOrmUIServer(s grpc.ServiceRegistrar, srv OrmUIServer) {
	s.RegisterService(&OrmUI_ServiceDesc, srv)
}

func _OrmUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrmUIServer).ListEngineSpecs(m, &ormUIListEngineSpecsServer{stream})
}

type OrmUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type ormUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *ormUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _OrmUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrmUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.OrmUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrmUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrmUI_ServiceDesc is the grpc.ServiceDesc for OrmUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrmUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.OrmUI",
	HandlerType: (*OrmUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _OrmUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _OrmUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "orm-ui.proto",
}
